package com.example.app;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;

public class ActivityU6 extends AppCompatActivity {

    TextView tvu61, tvu62;
    ListView lvu6;
    ArrayList<String> arru6;
    ArrayAdapter<String> adapu6;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_u6);

        tvu61 = findViewById(R.id.tvu61);
        tvu62 = findViewById(R.id.tvu62);
        lvu6 = findViewById(R.id.lvu6);

        tvu61.setText("Uses of Inductors");
        tvu62.setVisibility(View.GONE);

        arru6 = new ArrayList<String>();

        arru6.add("Tuning Circuits");
        arru6.add("Inductive Sensors");
        arru6.add("Induction Motors");
        arru6.add("Inductive Filters");
        arru6.add("Chokes");
        arru6.add("Relays");

        adapu6 = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, arru6);
        lvu6.setAdapter(adapu6);

        lvu6.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

                String def = new String();

                if(position == 0){
                    def = "Inductors are used in tuning circuits which are used to select the desired frequency. In a tuned circuit, we have capacitor connected along with the inductor, either in parallel or series. The frequency of the tuning circuit at which the capacitive reactance is equal to the inductive reactance (XC = XL) is called ‘Resonant Frequency’." + "\n" + "\n The series resonance circuits are used in many electronic circuits like television , radio tuning circuits and filters to vary the frequency and selecting the various frequency channels.";
                }

                if(position == 1){
                    def = "Inductors are used in proximity sensors which work on the principle of inductance. We know that inductance is the phenomenon in which , the magnetic field produced in the coil , will oppose the flow of current in it. So thus the inductance will restrict the current flow and reduces the circuit performance." + "\n" + "\n In the inductive proximity sensor, a fluctuating magnetic field is generated by oscillator around the winding of coil, which locates in the sensing face of the device. When an object moves in the field of inductive proximity area of detection, eddy currents starts building up in the metal object which will reduce the inductive sensor’s magnetic field.";
                }

                if(position == 2){
                    def = "The well known and wide range application of inductors is Induction motors. In these induction motors or asynchronous motors, the inductors are in fixed position and they did not allowed to move in nearby magnetic field." + "\n" + "\n Induction motors converts the electrical energy into mechanical energy. The shaft in the motors will rotate because of the magnetic field produced by the alternating current." + "\n" + "\n The speed of the motor is fixed as it depends on the frequency of the power supplied from source. So we use inductors in these motors to control the speed by connecting them in series or parallel to shaft. These induction motors are very reliable and robust.";
                }

                if(position == 3){
                    def = "Inductors and capacitors are combinely used to form filters. The filters are the electronic devices which are used to limit the frequency of the input signal entering to a circuit. There are many types of filters like low pass filter, high pass filter, band pass filter, notch filter etc which are designed by using inductors." + "\n" + "\n As the frequency increases, the impedance of the inductor also increases. Then the properties of filter will change according to the impedance value. There are many number of filter topologies we can create by using inductors.";
                }

                if(position == 4){
                    def = "Inductors are also used as chokes. We know that the inductors will create an opposite current flow, when the alternating current flows through it. This means the inductors will choke the AC current and allows DC current to pass. This property of inductors is used in power supply circuits, where AC supply need to be converted to DC supply.";
                }

                if(position == 5){
                    def = "A relay is like an electrical switch. It uses inductor coil to control the current flow in it. When the AC current flows through the inductor of the relay, it produces a magnetic field which effects the switch contacts.";
                }

                tvu62.setText(def);
                tvu62.setVisibility(View.VISIBLE);
            }
        });
    }
}